In [1]:
import pandas as pd
import numpy as np
import random
import csv
#%pdb
mypath = ('E:/OneDrive - University College London/Random_probes_last/Luca/')
#mypath = 'C:/Users/KeK/OneDrive - University College London/Random_probes_last/Luca/'

In [ ]:
def clean_csv(path):

In [2]:
def print_full(x):
    pd.set_option('display.max_rows', len(x))
    print(x)
    pd.reset_option('display.max_rows')

In [3]:
df1 = pd.DataFrame.from_csv(mypath+'p5_1_ready.csv', header = None)
df1.reset_index(inplace = True)
df1.columns = ['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','Load','exemplar','question','present_absent','trial_type','tone_Hz','tone_onset','space','RT_TO','keys','RT_VS','useless','Trial_N_Block','Block']
df1.shape
#df

(480, 21)

In [4]:
df2 = pd.DataFrame.from_csv(mypath+'p5_2_ready.csv', header = None)
df2.reset_index(inplace = True)
df2.columns = ['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','Load','exemplar','question','present_absent','trial_type','tone_Hz','tone_onset','space','RT_TO','keys','RT_VS','useless','Trial_N_Block','Block']
df2.shape
#df2

(480, 21)

In [5]:
frames = [df1,df2]
df = pd.concat(frames)
df.reset_index(drop=True)
df.drop(['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','exemplar','question','space','useless'], axis=1, inplace=True)
df

,Load,present_absent,trial_type,tone_Hz,tone_onset,RT_TO,keys,RT_VS,Trial_N_Block,Block
0,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',0,1
1,'low','Target Absent','Normal','No tone',-999,'No timing','p',2.842,1,1
2,'low','No Target','Critical','tone2',481,1.460890014,'Na','Na',2,1
3,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',3,1
4,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',4,1
5,'low','Target Present','Normal','No tone',-999,'No timing','q',2.138,5,1
6,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',6,1
7,'low','Target Present','Normal','No tone',-999,'No timing','q',2.482,7,1
8,'low','Target Absent','Normal','No tone',-999,'No timing','p',2.131,8,1
9,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',9,1
10,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',10,1
11,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',11,1
12,'low','No Target','Critical','tone2',631,1.395144772,'Na','Na',12,1
13,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',13,1
14,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',14,1
15,'low','No Target','Critical','tone2',305,1.111763832,'Na','Na',15,1
16,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',16,1
17,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',17,1
18,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',18,1
19,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',19,1
20,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',20,1
21,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',21,1
22,'low','No Target','Critical','tone1',78,0.861891771,'Na','Na',22,1
23,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',23,1
24,'low','No Target','Critical','tone2',946,1.461830845,'Na','Na',24,1
25,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',25,1
26,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',26,1
27,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',27,1
28,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',28,1
29,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',29,1
...,...,...,...,...,...,...,...,...,...,...
450,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',30,16
451,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',31,16
452,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',32,16
453,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',33,16
454,'high','No Target','Critical','tone1',385,'No timing','Na','Na',34,16
455,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',35,16
456,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',36,16
457,'high','Target Present','Normal','No tone',-999,'No timing','q',2.139,37,16
458,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',38,16
459,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',39,16
460,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',40,16
461,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',41,16
462,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',42,16
463,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',43,16
464,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',44,16
465,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',45,16
466,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',46,16
467,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',47,16
468,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',48,16
469,'high','Target Present','Normal','No tone',-999,'No timing','q',2.902,49,16
470,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',50,16
471,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',51,16
472,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',52,16
473,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',53,16
474,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',54,16
475,'high','Target Present','Normal','No tone',-999,'No timing','q',2.05,55,16
476,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',56,16
477,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',57,16
478,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',58,16
479,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',59,16

In [6]:
RT_TO = df['RT_TO'].tolist()
RT_VS = df['RT_VS'].tolist()
Audio = df['trial_type'].tolist()
Present_absent = df['present_absent'].tolist()
Audio = df['trial_type'].tolist()
Keys = df['keys'].tolist()
Tone_onset = df['tone_onset'].tolist()

In [7]:
#RT_TO_floats = [n for n in RT_TO if 'NaN' not in n]
#sd_TO = np.std(RT_TO_floats)
#mean_TO = np.mean(RT_TO_floats)

In [8]:
RT_TO = [str('NaN') if 'No timing' in n else float(n[0:5]) for n in RT_TO]

In [9]:
RT_VS = [str('NaN') if 'Na' in n else float(n[0:5])-1.3 for n in RT_VS]

In [10]:
Keys = [str(n[2:-1]) for n in Keys]

In [11]:
RT_TO_floats = [n for n in RT_TO if type(n) == float]
sd_TO = np.std(RT_TO_floats)
mean_TO = np.mean(RT_TO_floats)

In [12]:
#Getting rid of outliers for TO RT (outliers are replaced with mean)
RT_TO_no_outliers = []
counter_TO = 0
RT_TO_outliers = []
for i in RT_TO:
    if type(i) != float:
        RT_TO_no_outliers.append(i)
    elif type(i) == float:
        if (mean_TO - 2.5 * sd_TO) < i < (mean_TO + 2.5 * sd_TO):
            RT_TO_no_outliers.append(i)
        else:
            counter_TO = counter_TO + 1
            #print 'Outlier ' + str(counter_TO) + ': ' + str(i) 
            RT_TO_no_outliers.append(mean_TO)
            RT_TO_outliers.append(i)
RT_TO = RT_TO_no_outliers

In [13]:
Tone_onset = [int(n) for n in Tone_onset]
for i in range(len(Tone_onset)):
    if Tone_onset[i] != -999:
        Tone_onset[i] = float(Tone_onset[i])/1000
        if type(RT_TO[i]) == float:
            #print RT_TO[i], '-', Tone_onset[i] 
            RT_TO[i] = RT_TO[i] - Tone_onset[i]
            #print RT_TO[i]

In [14]:
RT_VS_floats = [n for n in RT_VS if type(n) == float]
sd_VS = np.std(RT_VS_floats)
mean_VS = np.mean(RT_VS_floats)

In [15]:
#Getting rid of outliers for TO RT (outliers are replaced with mean)
RT_VS_no_outliers = []
counter_VS = 0
RT_VS_outliers = []
for i in RT_VS:
    if type(i) != float:
        RT_VS_no_outliers.append(i)
    elif type(i) == float:
        if (mean_VS - 2.5 * sd_VS) < i < (mean_VS + 2.5 * sd_VS):
            RT_VS_no_outliers.append(i)
        else:
            counter_VS = counter_VS + 1
            #print 'Outlier ' + str(counter_TO) + ': ' + str(i) 
            RT_VS_no_outliers.append(mean_VS)
            RT_VS_outliers.append(i)
RT_VS = RT_VS_no_outliers

In [16]:
print 'Take Over:'
print 'mean RT: ', mean_TO
print 'SD: ', sd_TO
print 'Outliers: ', len(RT_TO_outliers)
for i in RT_TO_outliers:
    print i

print 'Visual Search:'
print 'mean RT: ', mean_VS
print 'SD: ', sd_VS
print 'Outliers: ', len(RT_VS_outliers)
for i in RT_VS_outliers:
    print i

Take Over:
mean RT:  1.394875
SD:  0.780216882908
Outliers:  2
-1.87
-3.5
Visual Search:
mean RT:  1.16585416667
SD:  0.440441397425
Outliers:  5
2.875
2.557
3.208
2.578
2.396

In [17]:
for i in RT_TO:
    print i, type(i)

NaN <type 'str'>
NaN <type 'str'>
0.979 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.764 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.806 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.783 <type 'float'>
NaN <type 'str'>
0.515 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.777 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.777 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.842 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
2.202 <type 'float'>
NaN <type 'str'>
0.713 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.914 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.75 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.393 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.809 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.793 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.573 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.646 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.632 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.534 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.069 <type 'float'>
NaN <type 'str'>
0.774 <type 'float'>
NaN <type 'str'>
1.132 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.948 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.02 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.838 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.833 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.852 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.14 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.777 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.251 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.999 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.061 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
1.32 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.394875 <type 'numpy.float64'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.08 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.964 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.869 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.343 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.302 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.031 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.302 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.896 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.899 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.613 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.101 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.48 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.976 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.126 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.86 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.907 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.718 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.83 <type 'float'>
NaN <type 'str'>
1.194 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.824 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.126 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.799 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.48 <type 'float'>
NaN <type 'str'>
0.658 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.003 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.828 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.257 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.394875 <type 'numpy.float64'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.699 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.412 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.423 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.682 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.218 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.589 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.79 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.917 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.04 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.459 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.856 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.594 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.59 <type 'float'>
0.574 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.864 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.653 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.991 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
1.4 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>

In [18]:
#######
Acc_VS = []
for i in range(960):
    if 'Critical' in Audio[i]:
        #print i
        Acc_VS.append('999')
    elif 'Normal' in Audio[i] and RT_TO[i] != 'NaN':
        Acc_VS.append('666')
    elif 'Target Present' in Present_absent[i] and 'q' in Keys[i]:
        Acc_VS.append(1)
    elif 'Target Present' in Present_absent[i] and 'p' in Keys[i]:
        Acc_VS.append(0)
    elif 'Target Absent' in Present_absent[i] and 'p' in Keys[i]:
        Acc_VS.append(1)   
    elif 'Target Absent' in Present_absent[i] and 'q' in Keys[i]:
        Acc_VS.append(0)
    elif 'No Target' in Present_absent[i]:
        Acc_VS.append('999')

#print len(Acc_VS)
#######

In [19]:
#######
# CREATING Acc_DT (1 = included for analysis; 0 = excluded from analysis)
Acc_DT = []
for i in range(960):
    if 'Critical' in Audio[i] and type(RT_TO[i]) != str:
        if 'Target Present' in Present_absent[i] and 'q' in Keys[i]:
            Acc_DT.append(1)
        elif 'Target Absent' in Present_absent[i] and 'p' in Keys[i]:
            Acc_DT.append(1)
        elif 'Target Present' in Present_absent[i] and 'p' in Keys[i]:
            Acc_DT.append(999)
        elif 'Target Absent' in Present_absent[i] and 'q' in Keys[i]:
            Acc_DT.append(999)
        elif 'No Target' in Present_absent[i]:
            Acc_DT.append(1)
    elif 'Critical' in Audio[i] and type(RT_TO[i]) == str:
        Acc_DT.append(0)
    elif 'Normal' in Audio[i] and type(RT_TO[i]) != str:
        Acc_DT.append(666) # 666 are false alarms
    elif 'Normal' in Audio[i] and type(RT_TO[i]) == str:
        Acc_DT.append(999)
#print len(Acc_DT)

In [33]:
# Calculating D' :
# to calculate D' prime you need:
#1) hit rate
#2) false alarms rate
# the z-transformed of 1 and 2
# the formula is:....
# 1 and 2 cannot be equal to 1 or 0
correct_response_counter = len([n for n in Acc_DT if n == 1])
incorrect_response_counter = len([n for n in Acc_DT if n == 0])
incorrect_response_counter

19

In [21]:
# Converting lists into pandas.series...
RT_TO = pd.Series(data=RT_TO)
RT_VS = pd.Series(data=RT_VS)
Acc_VS = pd.Series(data=Acc_VS)
Acc_DT = pd.Series(data=Acc_DT)
#False_Alarms = pd.Series(data=False_Alarms)
# ...and combining them into a pandas dataframe

In [22]:
df.drop(['RT_TO','RT_VS'], inplace = True)
df['RT_TO'] = RT_TO.values
df['RT_VS'] = RT_VS.values
df['Acc_VS'] = Acc_VS.values
df['Acc_DT'] = Acc_DT.values

In [23]:
df[['RT_TO','RT_VS']] = df[['RT_TO','RT_VS']].astype('float')
df[['Acc_VS','Acc_DT']] = df[['Acc_VS','Acc_DT']].astype('int')
print df.dtypes

Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
RT_TO             float64
keys               object
RT_VS             float64
Trial_N_Block       int64
Block               int64
Acc_VS              int32
Acc_DT              int32
dtype: object

In [24]:
# Calculating D' :
# to calculate D' prime you need:
#1) hit rate
#2) false alarms rate
# the z-transformed of 1 and 2
# the formula is:....
# 1 and 2 cannot be equal to 1 or 0

In [25]:
#TABLE 1
#print df.groupby(['Load','Acc_VS']).RT_VS.mean()
#print df.groupby(['Load','Acc_VS']).RT_VS.count()

# TABLE 2
print df.groupby(['Load','Acc_VS','present_absent']).RT_VS.mean()
print df.groupby(['Load','Acc_VS','present_absent']).RT_VS.count()

#TABLE 3
#print df.groupby(['Load','trial_type','Acc_DT']).RT_TO.mean()
#print df.groupby(['Load','trial_type','Acc_DT']).Acc_DT.count()

#-----------------------------------------------------------------------
#TABLE 4
#print df.groupby(['Load','Audio']).Audio.count()
#print df.groupby(['Load','Audio','Acc_DT']).Acc_DT.count()

Load     Acc_VS  present_absent
 'high'  0        'Target Absent'     0.998800
                  'Target Present'    1.032200
         1        'Target Absent'     1.170548
                  'Target Present'    1.073960
         666      'No Target'              NaN
         999      'No Target'              NaN
                  'Target Absent'     0.953333
                  'Target Present'    0.929000
 'low'   0        'Target Absent'     1.208500
                  'Target Present'    1.370333
         1        'Target Absent'     1.156834
                  'Target Present'    1.056147
         666      'No Target'              NaN
         999      'No Target'              NaN
                  'Target Absent'     1.376971
Name: RT_VS, dtype: float64
Load     Acc_VS  present_absent
 'high'  0        'Target Absent'      5
                  'Target Present'    10
         1        'Target Absent'     25
                  'Target Present'    25
         666      'No Target'          0
         999      'No Target'          0
                  'Target Absent'      6
                  'Target Present'     1
 'low'   0        'Target Absent'      6
                  'Target Present'     3
         1        'Target Absent'     25
                  'Target Present'    33
         666      'No Target'          0
         999      'No Target'          0
                  'Target Absent'      5
Name: RT_VS, dtype: int64