In [22]:
from random import random

In [31]:
test

In [10]:
tdf.loc[2,'RT_TO']

nan

In [24]:
notes

{'rejects_TO': [0,
      Image_Name Cat.1 Cat.2 Cat.3 Cat.4 Cat.5   TS Load exemplar question  \
  1          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  2          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  3          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  4          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  5          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  6          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  7          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  8          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  9          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  10         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  11         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  12         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  13         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  14         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  15         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  16         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  17         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  18         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  19         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  20         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  21         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  22         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  23         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  24         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  25         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  26         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  27         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  28         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  29         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  30         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  ..         ...   ...   ...   ...   ...   ...  ...  ...      ...      ...
  371        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  372        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  373        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  374        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  375        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  376        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  377        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  378        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  379        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  380        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  381        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  382        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  383        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  384        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  385        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  386        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  387        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  388        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  389        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  390        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  391        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  392        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  393        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  394        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  395        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  396        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  397        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  398        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  399        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  400        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN

       ...  trial_type tone_Hz tone_onset space    RT_TO keys    RT_VS useless  \
  1    ...         NaN     NaN        NaN   NaN  453.669  NaN  453.669     NaN
  2    ...         NaN     NaN        NaN   NaN  469.624  NaN  469.624     NaN
  3    ...         NaN     NaN        NaN   NaN  470.543  NaN  470.543     NaN
  4    ...         NaN     NaN        NaN   NaN   487.82  NaN   487.82     NaN
  5    ...         NaN     NaN        NaN   NaN  456.196  NaN  456.196     NaN
  6    ...         NaN     NaN        NaN   NaN  463.708  NaN  463.708     NaN
  7    ...         NaN     NaN        NaN   NaN  462.122  NaN  462.122     NaN
  8    ...         NaN     NaN        NaN   NaN  468.479  NaN  468.479     NaN
  9    ...         NaN     NaN        NaN   NaN   484.22  NaN   484.22     NaN
  10   ...         NaN     NaN        NaN   NaN  496.235  NaN  496.235     NaN
  11   ...         NaN     NaN        NaN   NaN  495.515  NaN  495.515     NaN
  12   ...         NaN     NaN        NaN   NaN  476.547  NaN  476.547     NaN
  13   ...         NaN     NaN        NaN   NaN  463.657  NaN  463.657     NaN
  14   ...         NaN     NaN        NaN   NaN  489.695  NaN  489.695     NaN
  15   ...         NaN     NaN        NaN   NaN  452.723  NaN  452.723     NaN
  16   ...         NaN     NaN        NaN   NaN  478.869  NaN  478.869     NaN
  17   ...         NaN     NaN        NaN   NaN   457.13  NaN   457.13     NaN
  18   ...         NaN     NaN        NaN   NaN   457.37  NaN   457.37     NaN
  19   ...         NaN     NaN        NaN   NaN  484.433  NaN  484.433     NaN
  20   ...         NaN     NaN        NaN   NaN  462.534  NaN  462.534     NaN
  21   ...         NaN     NaN        NaN   NaN  491.775  NaN  491.775     NaN
  22   ...         NaN     NaN        NaN   NaN  461.959  NaN  461.959     NaN
  23   ...         NaN     NaN        NaN   NaN  489.199  NaN  489.199     NaN
  24   ...         NaN     NaN        NaN   NaN  463.591  NaN  463.591     NaN
  25   ...         NaN     NaN        NaN   NaN  451.109  NaN  451.109     NaN
  26   ...         NaN     NaN        NaN   NaN  450.531  NaN  450.531     NaN
  27   ...         NaN     NaN        NaN   NaN  461.676  NaN  461.676     NaN
  28   ...         NaN     NaN        NaN   NaN  483.851  NaN  483.851     NaN
  29   ...         NaN     NaN        NaN   NaN  499.864  NaN  499.864     NaN
  30   ...         NaN     NaN        NaN   NaN  478.294  NaN  478.294     NaN
  ..   ...         ...     ...        ...   ...      ...  ...      ...     ...
  371  ...         NaN     NaN        NaN   NaN  456.805  NaN  456.805     NaN
  372  ...         NaN     NaN        NaN   NaN  469.895  NaN  469.895     NaN
  373  ...         NaN     NaN        NaN   NaN  469.163  NaN  469.163     NaN
  374  ...         NaN     NaN        NaN   NaN  480.483  NaN  480.483     NaN
  375  ...         NaN     NaN        NaN   NaN  476.917  NaN  476.917     NaN
  376  ...         NaN     NaN        NaN   NaN  489.795  NaN  489.795     NaN
  377  ...         NaN     NaN        NaN   NaN  472.451  NaN  472.451     NaN
  378  ...         NaN     NaN        NaN   NaN  498.362  NaN  498.362     NaN
  379  ...         NaN     NaN        NaN   NaN  469.095  NaN  469.095     NaN
  380  ...         NaN     NaN        NaN   NaN  451.415  NaN  451.415     NaN
  381  ...         NaN     NaN        NaN   NaN  483.715  NaN  483.715     NaN
  382  ...         NaN     NaN        NaN   NaN  481.388  NaN  481.388     NaN
  383  ...         NaN     NaN        NaN   NaN  453.449  NaN  453.449     NaN
  384  ...         NaN     NaN        NaN   NaN  479.715  NaN  479.715     NaN
  385  ...         NaN     NaN        NaN   NaN  492.314  NaN  492.314     NaN
  386  ...         NaN     NaN        NaN   NaN  481.697  NaN  481.697     NaN
  387  ...         NaN     NaN        NaN   NaN  475.868  NaN  475.868     NaN
  388  ...         NaN     NaN        NaN   NaN  497.891  NaN  497.891     NaN
  389  ...         NaN     NaN        NaN   NaN  457.383  NaN  457.383     NaN
  390  ...         NaN     NaN        NaN   NaN  455.995  NaN  455.995     NaN
  391  ...         NaN     NaN        NaN   NaN  463.887  NaN  463.887     NaN
  392  ...         NaN     NaN        NaN   NaN  464.844  NaN  464.844     NaN
  393  ...         NaN     NaN        NaN   NaN  496.257  NaN  496.257     NaN
  394  ...         NaN     NaN        NaN   NaN  498.344  NaN  498.344     NaN
  395  ...         NaN     NaN        NaN   NaN  499.612  NaN  499.612     NaN
  396  ...         NaN     NaN        NaN   NaN  495.146  NaN  495.146     NaN
  397  ...         NaN     NaN        NaN   NaN  461.717  NaN  461.717     NaN
  398  ...         NaN     NaN        NaN   NaN  464.254  NaN  464.254     NaN
  399  ...         NaN     NaN        NaN   NaN  475.862  NaN  475.862     NaN
  400  ...         NaN     NaN        NaN   NaN  482.299  NaN  482.299     NaN

      Trial_N_Block Block
  1             NaN   NaN
  2             NaN   NaN
  3             NaN   NaN
  4             NaN   NaN
  5             NaN   NaN
  6             NaN   NaN
  7             NaN   NaN
  8             NaN   NaN
  9             NaN   NaN
  10            NaN   NaN
  11            NaN   NaN
  12            NaN   NaN
  13            NaN   NaN
  14            NaN   NaN
  15            NaN   NaN
  16            NaN   NaN
  17            NaN   NaN
  18            NaN   NaN
  19            NaN   NaN
  20            NaN   NaN
  21            NaN   NaN
  22            NaN   NaN
  23            NaN   NaN
  24            NaN   NaN
  25            NaN   NaN
  26            NaN   NaN
  27            NaN   NaN
  28            NaN   NaN
  29            NaN   NaN
  30            NaN   NaN
  ..            ...   ...
  371           NaN   NaN
  372           NaN   NaN
  373           NaN   NaN
  374           NaN   NaN
  375           NaN   NaN
  376           NaN   NaN
  377           NaN   NaN
  378           NaN   NaN
  379           NaN   NaN
  380           NaN   NaN
  381           NaN   NaN
  382           NaN   NaN
  383           NaN   NaN
  384           NaN   NaN
  385           NaN   NaN
  386           NaN   NaN
  387           NaN   NaN
  388           NaN   NaN
  389           NaN   NaN
  390           NaN   NaN
  391           NaN   NaN
  392           NaN   NaN
  393           NaN   NaN
  394           NaN   NaN
  395           NaN   NaN
  396           NaN   NaN
  397           NaN   NaN
  398           NaN   NaN
  399           NaN   NaN
  400           NaN   NaN

  [400 rows x 21 columns]],
 'rejects_VS': (0,
      Image_Name Cat.1 Cat.2 Cat.3 Cat.4 Cat.5   TS Load exemplar question  \
  1          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  2          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  3          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  4          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  5          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  6          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  7          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  8          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  9          NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  10         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  11         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  12         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  13         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  14         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  15         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  16         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  17         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  18         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  19         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  20         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  21         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  22         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  23         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  24         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  25         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  26         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  27         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  28         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  29         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  30         NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  ..         ...   ...   ...   ...   ...   ...  ...  ...      ...      ...
  371        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  372        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  373        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  374        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  375        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  376        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  377        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  378        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  379        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  380        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  381        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  382        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  383        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  384        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  385        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  386        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  387        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  388        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  389        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  390        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  391        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  392        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  393        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  394        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  395        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  396        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  397        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  398        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  399        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN
  400        NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN      NaN      NaN

       ...  trial_type tone_Hz tone_onset space    RT_TO keys    RT_VS useless  \
  1    ...         NaN     NaN        NaN   NaN  453.669  NaN  453.669     NaN
  2    ...         NaN     NaN        NaN   NaN  469.624  NaN  469.624     NaN
  3    ...         NaN     NaN        NaN   NaN  470.543  NaN  470.543     NaN
  4    ...         NaN     NaN        NaN   NaN   487.82  NaN   487.82     NaN
  5    ...         NaN     NaN        NaN   NaN  456.196  NaN  456.196     NaN
  6    ...         NaN     NaN        NaN   NaN  463.708  NaN  463.708     NaN
  7    ...         NaN     NaN        NaN   NaN  462.122  NaN  462.122     NaN
  8    ...         NaN     NaN        NaN   NaN  468.479  NaN  468.479     NaN
  9    ...         NaN     NaN        NaN   NaN   484.22  NaN   484.22     NaN
  10   ...         NaN     NaN        NaN   NaN  496.235  NaN  496.235     NaN
  11   ...         NaN     NaN        NaN   NaN  495.515  NaN  495.515     NaN
  12   ...         NaN     NaN        NaN   NaN  476.547  NaN  476.547     NaN
  13   ...         NaN     NaN        NaN   NaN  463.657  NaN  463.657     NaN
  14   ...         NaN     NaN        NaN   NaN  489.695  NaN  489.695     NaN
  15   ...         NaN     NaN        NaN   NaN  452.723  NaN  452.723     NaN
  16   ...         NaN     NaN        NaN   NaN  478.869  NaN  478.869     NaN
  17   ...         NaN     NaN        NaN   NaN   457.13  NaN   457.13     NaN
  18   ...         NaN     NaN        NaN   NaN   457.37  NaN   457.37     NaN
  19   ...         NaN     NaN        NaN   NaN  484.433  NaN  484.433     NaN
  20   ...         NaN     NaN        NaN   NaN  462.534  NaN  462.534     NaN
  21   ...         NaN     NaN        NaN   NaN  491.775  NaN  491.775     NaN
  22   ...         NaN     NaN        NaN   NaN  461.959  NaN  461.959     NaN
  23   ...         NaN     NaN        NaN   NaN  489.199  NaN  489.199     NaN
  24   ...         NaN     NaN        NaN   NaN  463.591  NaN  463.591     NaN
  25   ...         NaN     NaN        NaN   NaN  451.109  NaN  451.109     NaN
  26   ...         NaN     NaN        NaN   NaN  450.531  NaN  450.531     NaN
  27   ...         NaN     NaN        NaN   NaN  461.676  NaN  461.676     NaN
  28   ...         NaN     NaN        NaN   NaN  483.851  NaN  483.851     NaN
  29   ...         NaN     NaN        NaN   NaN  499.864  NaN  499.864     NaN
  30   ...         NaN     NaN        NaN   NaN  478.294  NaN  478.294     NaN
  ..   ...         ...     ...        ...   ...      ...  ...      ...     ...
  371  ...         NaN     NaN        NaN   NaN  456.805  NaN  456.805     NaN
  372  ...         NaN     NaN        NaN   NaN  469.895  NaN  469.895     NaN
  373  ...         NaN     NaN        NaN   NaN  469.163  NaN  469.163     NaN
  374  ...         NaN     NaN        NaN   NaN  480.483  NaN  480.483     NaN
  375  ...         NaN     NaN        NaN   NaN  476.917  NaN  476.917     NaN
  376  ...         NaN     NaN        NaN   NaN  489.795  NaN  489.795     NaN
  377  ...         NaN     NaN        NaN   NaN  472.451  NaN  472.451     NaN
  378  ...         NaN     NaN        NaN   NaN  498.362  NaN  498.362     NaN
  379  ...         NaN     NaN        NaN   NaN  469.095  NaN  469.095     NaN
  380  ...         NaN     NaN        NaN   NaN  451.415  NaN  451.415     NaN
  381  ...         NaN     NaN        NaN   NaN  483.715  NaN  483.715     NaN
  382  ...         NaN     NaN        NaN   NaN  481.388  NaN  481.388     NaN
  383  ...         NaN     NaN        NaN   NaN  453.449  NaN  453.449     NaN
  384  ...         NaN     NaN        NaN   NaN  479.715  NaN  479.715     NaN
  385  ...         NaN     NaN        NaN   NaN  492.314  NaN  492.314     NaN
  386  ...         NaN     NaN        NaN   NaN  481.697  NaN  481.697     NaN
  387  ...         NaN     NaN        NaN   NaN  475.868  NaN  475.868     NaN
  388  ...         NaN     NaN        NaN   NaN  497.891  NaN  497.891     NaN
  389  ...         NaN     NaN        NaN   NaN  457.383  NaN  457.383     NaN
  390  ...         NaN     NaN        NaN   NaN  455.995  NaN  455.995     NaN

In [29]:
tdf = gen_test()
out_df,notes = process(tdf)

MEAN TO:  473.756391975
WINDOW:  374.323373188 573.189410763
TO rejects n:  12
VS rejects N:  12

In [22]:
tdf['RT_TO']

1      453.669
2      469.624
3      470.543
4       487.82
5      456.196
6      463.708
7      462.122
8      468.479
9       484.22
10     496.235
11     495.515
12     476.547
13     463.657
14     489.695
15     452.723
16     478.869
17      457.13
18      457.37
19     484.433
20     462.534
21     491.775
22     461.959
23     489.199
24     463.591
25     451.109
26     450.531
27     461.676
28     483.851
29     499.864
30     478.294
        ...
371    456.805
372    469.895
373    469.163
374    480.483
375    476.917
376    489.795
377    472.451
378    498.362
379    469.095
380    451.415
381    483.715
382    481.388
383    453.449
384    479.715
385    492.314
386    481.697
387    475.868
388    497.891
389    457.383
390    455.995
391    463.887
392    464.844
393    496.257
394    498.344
395    499.612
396    495.146
397    461.717
398    464.254
399    475.862
400    482.299
Name: RT_TO, Length: 400, dtype: object

In [1]:
import pandas as pd
import numpy as np
import random
import csv
from pdb import set_trace
import pdb
#%pdb
mypath = 'E:/OneDrive - University College London/load/pilot_6_data/'
#mypath = 'C:/Users/KeK/OneDrive - University College London/load/pilot_6_data/'
%load_ext autoreload
%autoreload 2

from process import *
from test import *

In [21]:
df,notes = process('test')

ValueError: Incompatible indexer with Series

In [19]:
test = df[df['RT_TO'].between(3,4)]

In [35]:
f = '../output/participant_test.pik'
import pickle
with open(f,'r') as of:
    D = pickle.load(of)
new_df = pd.DataFrame.from_dict(D['experiment_details'],orient='index')

In [36]:
new_df

,cat_4,cat_5,tone_hz,tone_onset,cat_1,cat_2,cat_3,keys,space,question,...,load,present_absent,block_number,RT_VS,exemplar,trueskill,RT_TO,trial_type,image_number,useless
1,NaN,NaN,No tone,-999,cat,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,cat,12.729033,6.666,Normal,0,NaN
2,NaN,NaN,No tone,-999,horse,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,horse,19.234401,6.666,Normal,1,NaN
3,NaN,NaN,No tone,-999,person,sofa,NaN,None,space,NaN,...,low,No Target,1,NaN,sofa,19.244036,6.666,Normal,2,NaN
4,NaN,NaN,No tone,-999,car,person,NaN,None,space,NaN,...,low,No Target,1,NaN,car,20.695715,6.666,Normal,3,NaN
5,NaN,NaN,No tone,-999,dog,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,dog,20.074686,6.666,Normal,4,NaN
6,NaN,NaN,No tone,-999,boat,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,boat,20.210044,6.666,Normal,5,NaN
7,NaN,NaN,No tone,-999,boat,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,boat,21.198620,6.666,Normal,6,NaN
8,NaN,NaN,No tone,-999,boat,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,boat,16.846337,6.666,Normal,7,NaN
9,NaN,NaN,No tone,-999,bottle,NaN,NaN,q,space,bird,...,low,Target Absent,1,6.66,bottle,19.096237,6.666,Normal,8,-999.0
10,NaN,NaN,No tone,-999,dog,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,dog,17.102590,6.666,Normal,9,NaN
11,NaN,NaN,No tone,-999,person,dog,NaN,None,space,NaN,...,low,No Target,1,NaN,dog,20.712899,6.666,Normal,10,NaN
12,NaN,NaN,No tone,-999,cat,NaN,NaN,q,space,cat,...,low,Target Present,1,6.66,cat,20.463884,6.666,Normal,11,-999.0
13,NaN,NaN,No tone,-999,car,NaN,NaN,q,space,boat,...,low,Target Absent,1,6.66,car,19.030178,6.666,Normal,12,-999.0
14,NaN,NaN,No tone,-999,person,bottle,NaN,None,space,NaN,...,low,No Target,1,NaN,bottle,19.869099,6.666,Normal,13,NaN
15,NaN,NaN,No tone,-999,person,boat,NaN,None,space,NaN,...,low,No Target,1,NaN,person,18.642450,6.666,Normal,14,NaN
16,NaN,NaN,No tone,-999,person,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,person,15.903696,6.666,Normal,15,NaN
17,NaN,NaN,No tone,-999,person,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,person,21.051373,6.666,Normal,16,NaN
18,NaN,NaN,No tone,-999,person,cat,NaN,None,space,NaN,...,low,No Target,1,NaN,person,20.139878,6.666,Normal,17,NaN
19,NaN,NaN,No tone,-999,horse,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,horse,20.957748,6.666,Normal,18,NaN
20,NaN,NaN,No tone,-999,dog,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,dog,18.045036,6.666,Normal,19,NaN
21,NaN,NaN,No tone,-999,person,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,person,18.879558,6.666,Normal,20,NaN
22,NaN,NaN,No tone,-999,bottle,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,bottle,16.598875,6.666,Normal,21,NaN
23,NaN,NaN,No tone,-999,boat,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,boat,19.253520,6.666,Normal,22,NaN
24,NaN,NaN,No tone,-999,cat,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,cat,20.537354,6.666,Normal,23,NaN
25,NaN,NaN,No tone,-999,sofa,person,NaN,None,space,NaN,...,low,No Target,1,NaN,sofa,20.983298,6.666,Normal,24,NaN
26,NaN,NaN,No tone,-999,chair,diningtable,NaN,None,space,NaN,...,low,No Target,1,NaN,chair,20.735146,6.666,Normal,25,NaN
27,NaN,NaN,No tone,-999,bird,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,bird,19.239146,6.666,Normal,26,NaN
28,NaN,NaN,tone1,765,dog,bottle,NaN,None,space,NaN,...,low,No Target,1,NaN,bottle,18.860703,6.666,Critical,27,NaN
29,NaN,NaN,No tone,-999,aeroplane,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,aeroplane,20.158044,6.666,Normal,28,NaN
30,NaN,NaN,No tone,-999,boat,NaN,NaN,None,space,NaN,...,low,No Target,1,NaN,boat,19.264338,6.666,Normal,29,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,tvmonitor,chair,No tone,-999,person,bottle,pottedplant,None,space,NaN,...,high,No Target,16,NaN,bottle,31.676386,6.666,Normal,30,NaN
932,NaN,NaN,No tone,-999,person,horse,NaN,None,space,NaN,...,high,No Target,16,NaN,horse,30.530490,6.666,Normal,31,NaN
933,NaN,NaN,No tone,-999,sofa,chair,person,None,space,NaN,...,high,No Target,16,NaN,sofa,36.443792,6.666,Normal,32,NaN
934,NaN,NaN,No tone,-999,person,sofa,cat,q,space,cat,...,high,Target Present,16,6.66,cat,29.514190,6.666,Normal,33,-999.0
935,NaN,NaN,No tone,-999,person,bird,boat,None,space,NaN,...,high,No Target,16,NaN,bird,31.913410,6.666,Normal,34,NaN
936,NaN,NaN,No tone,-999,pottedplant,chair,NaN,None,space,NaN,...,high,No Target,16,NaN,pottedplant,34.966628,6.666,Normal,35,NaN
937,NaN,NaN,No tone,-999,boat,cow,NaN,q,space,boat,...,high,Target Present,16,6.66,boat,29.659407,6.666,Normal,36,-999.0
938,NaN,NaN,No tone,-999,person,diningtable,bottle,None,space,NaN,...,high,No Target,16,NaN,bottle,38.972642,6.666,Normal,37,NaN
939,NaN,NaN,No tone,-999,bird,boat,NaN,None,space,NaN,...,high,No Target,16,NaN,bird,29.314234,6.666,Normal,38,NaN
940,NaN,NaN,No tone,-999,person,aeroplane,NaN,None,space,NaN,...,high,No Target,16,NaN,aeroplane,31.885878,6.666,Normal,39,NaN
941,NaN,NaN,No tone,-999,car,NaN,NaN,None,space,NaN,...,high,No Target,16,NaN,car,30.394048,6.666,Normal,40,NaN
942,NaN,NaN,No tone,-999,car,person,bus,q,space,bird,...,high,Target Absent,16,6.66,car,35.069419,6.666,Normal,41,-999.0
943,NaN,NaN,tone2,786,person,horse,NaN,None,space,NaN,...,high,No Target,16,NaN,horse,31.310600,6.666,Critical,42,NaN
944,NaN,NaN,No tone,-999,chair,diningtable,NaN,None,space,NaN,...,high,No Target,16,NaN,chair,29.119691,6.666,Normal,43,NaN
945,NaN,NaN,No tone,-999,person,horse,NaN,None,space,NaN,...,high,No Target,16,NaN,horse,29.265462,6.666,Normal,44,NaN
946,NaN,NaN,No tone,-999,chair,bottle,NaN,None,space,NaN,...,high,No Target,16,NaN,chair,30.424874,6.666,Normal,45,NaN
947,NaN,NaN,tone1,448,tvmonitor,diningtable,cat,None,space,NaN,...,high,No Target,16,NaN,cat,29.842923,6.666,Critical,46,NaN
948,NaN,NaN,No tone,-999,dog,NaN,NaN,None,space,NaN,...,high,No Target,16,NaN,dog,40.773121,6.666,Normal,47,NaN
949,NaN,NaN,No tone,-999,car,cat,NaN,None,space,NaN,...,high,No Target,16,NaN,cat,33.462185,6.666,Normal,48,NaN
950,NaN,NaN,No tone,-999,cat,NaN,NaN,None,space,NaN,...,high,No Target,16,NaN,cat,31.779859,6.666,Normal,49,NaN
951,NaN,NaN,No tone,-999,bird,NaN,NaN,None,space,NaN,...,high,No Target,16,NaN,bird,29.176311,6.666,Normal,50,NaN
952,NaN,NaN,No tone,-999,car,boat,person,None,space,NaN,...,high,No Target,16,NaN,boat,32.759267,6.666,Normal,51,NaN
953,NaN,NaN,No tone,-999,person,aeroplane,NaN,q,space,pottedplant,...,high,Target Absent,16,6.66,aeroplane,30.242937,6.666,Normal,52,-999.0
954,bottle,NaN,No tone,-999,pottedplant,person,diningtable,None,space,NaN,...,high,No Target,16,NaN,pottedplant,28.939513,6.666,Normal,53,NaN
955,NaN,NaN,No tone,-999,person,cat,NaN,None,space,NaN,...,high,No Target,16,NaN,cat,32.265109,6.666,Normal,54,NaN
956,NaN,NaN,No tone,-999,pottedplant,person,dog,None,space,NaN,...,high,No Target,16,NaN,dog,30.007374,6.666,Normal,55,NaN
957,NaN,NaN,No tone,-999,person,bottle,sofa,None,space,NaN,...,high,No Target,16,NaN,bottle,33.561186,6.666,Normal,56,NaN
958,NaN,NaN,No tone,-999,person,diningtable,bottle,q,space,sofa,...,high,Target Absent,16,6.66,bottle,36.485056,6.666,Normal,57,-999.0
959,NaN,NaN,No tone,-999,person,chair,bottle,q,space,chair,...,high,Target Present,16,6.66,chair,33.381115,6.666,Normal,58,-999.0
960,NaN,NaN,tone2,536,boat,NaN,NaN,None,space,NaN,...,high,No Target,16,NaN,boat,34.967528,6.666,Critical,59,NaN

In [34]:
D['experiment_details'][1].keys()

['cat_4',
 'cat_5',
 'tone_hz',
 'tone_onset',
 'cat_1',
 'cat_2',
 'cat_3',
 'keys',
 'space',
 'question',
 'image_name',
 'load',
 'present_absent',
 'block_number',
 'RT_VS',
 'exemplar',
 'trueskill',
 'RT_TO',
 'trial_type',
 'image_number',
 'useless']

In [13]:
df['RT_VS'].between(0, 10, inclusive=False)

1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
       ...
931    False
932    False
933    False
934    False
935    False
936    False
937    False
938    False
939    False
940    False
941    False
942    False
943    False
944    False
945    False
946    False
947    False
948    False
949    False
950    False
951    False
952    False
953    False
954    False
955    False
956    False
957    False
958    False
959    False
960    False
Name: RT_VS, Length: 960, dtype: bool

In [5]:
df['RT_TO'].between(low, high, inclusive=False).mean()

NameError: name 'low' is not defined

In [6]:
df

,Image_Name,Cat.1,Cat.2,Cat.3,Cat.4,Cat.5,TS,Load,exemplar,question,...,trial_type,tone_Hz,tone_onset,space,RT_TO,keys,RT_VS,useless,Trial_N_Block,Block
1,2009_004225.jpg,cat,NaN,NaN,NaN,NaN,12.729,low,cat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
2,2010_001829.jpg,horse,NaN,NaN,NaN,NaN,19.2344,low,horse,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
3,2008_004270.jpg,person,sofa,NaN,NaN,NaN,19.244,low,sofa,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
4,2011_002303.jpg,car,person,NaN,NaN,NaN,20.6957,low,car,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
5,2010_005885.jpg,dog,NaN,NaN,NaN,NaN,20.0747,low,dog,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
6,2008_001040.jpg,boat,NaN,NaN,NaN,NaN,20.21,low,boat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
7,2010_004662.jpg,boat,NaN,NaN,NaN,NaN,21.1986,low,boat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
8,2010_005780.jpg,boat,NaN,NaN,NaN,NaN,16.8463,low,boat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
9,2009_002594.jpg,bottle,NaN,NaN,NaN,NaN,19.0962,low,bottle,bird,...,Normal,No tone,-999,space,0,q,0,-999,0,1
10,2009_001568.jpg,dog,NaN,NaN,NaN,NaN,17.1026,low,dog,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
11,2008_005046.jpg,person,dog,NaN,NaN,NaN,20.7129,low,dog,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
12,2008_001836.jpg,cat,NaN,NaN,NaN,NaN,20.4639,low,cat,cat,...,Normal,No tone,-999,space,0,q,0,-999,0,1
13,2009_004594.jpg,car,NaN,NaN,NaN,NaN,19.0302,low,car,boat,...,Normal,No tone,-999,space,0,q,0,-999,0,1
14,2008_004814.jpg,person,bottle,NaN,NaN,NaN,19.8691,low,bottle,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
15,2008_008083.jpg,person,boat,NaN,NaN,NaN,18.6425,low,person,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
16,2008_001098.jpg,person,NaN,NaN,NaN,NaN,15.9037,low,person,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
17,2008_002700.jpg,person,NaN,NaN,NaN,NaN,21.0514,low,person,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
18,2009_002439.jpg,person,cat,NaN,NaN,NaN,20.1399,low,person,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
19,2009_003232.jpg,horse,NaN,NaN,NaN,NaN,20.9577,low,horse,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
20,2010_000811.jpg,dog,NaN,NaN,NaN,NaN,18.045,low,dog,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
21,2008_002145.jpg,person,NaN,NaN,NaN,NaN,18.8796,low,person,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
22,2010_002956.jpg,bottle,NaN,NaN,NaN,NaN,16.5989,low,bottle,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
23,2009_000919.jpg,boat,NaN,NaN,NaN,NaN,19.2535,low,boat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
24,2009_000716.jpg,cat,NaN,NaN,NaN,NaN,20.5374,low,cat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
25,2008_004269.jpg,sofa,person,NaN,NaN,NaN,20.9833,low,sofa,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
26,2010_001271.jpg,chair,diningtable,NaN,NaN,NaN,20.7351,low,chair,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
27,2011_002582.jpg,bird,NaN,NaN,NaN,NaN,19.2391,low,bird,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
28,2010_000805.jpg,dog,bottle,NaN,NaN,NaN,18.8607,low,bottle,NaN,...,Critical,tone1,765,space,0,None,None,None,0,1
29,2008_007096.jpg,aeroplane,NaN,NaN,NaN,NaN,20.158,low,aeroplane,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
30,2009_001723.jpg,boat,NaN,NaN,NaN,NaN,19.2643,low,boat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,2010_002742.jpg,person,bottle,pottedplant,tvmonitor,chair,31.6764,high,bottle,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
932,2009_000565.jpg,person,horse,NaN,NaN,NaN,30.5305,high,horse,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
933,2011_002971.jpg,sofa,chair,person,NaN,NaN,36.4438,high,sofa,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
934,2010_005606.jpg,person,sofa,cat,NaN,NaN,29.5142,high,cat,cat,...,Normal,No tone,-999,space,0,q,0,-999,0,16
935,2011_001001.jpg,person,bird,boat,NaN,NaN,31.9134,high,bird,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
936,2009_000198.jpg,pottedplant,chair,NaN,NaN,NaN,34.9666,high,pottedplant,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
937,2008_002709.jpg,boat,cow,NaN,NaN,NaN,29.6594,high,boat,boat,...,Normal,No tone,-999,space,0,q,0,-999,0,16
938,2010_001645.jpg,person,diningtable,bottle,NaN,NaN,38.9726,high,bottle,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
939,2008_006481.jpg,bird,boat,NaN,NaN,NaN,29.3142,high,bird,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
940,2008_006216.jpg,person,aeroplane,NaN,NaN,NaN,31.8859,high,aeroplane,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
941,2008_002672.jpg,car,NaN,NaN,NaN,NaN,30.394,high,car,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
942,2008_000982.jpg,car,person,bus,NaN,NaN,35.0694,high,car,bird,...,Normal,No tone,-999,space,0,q,0,-999,0,16
943,2011_000628.jpg,person,horse,NaN,NaN,NaN,31.3106,high,horse,NaN,...,Critical,tone2,786,space,0,None,None,None,0,16
944,2009_003520.jpg,chair,diningtable,NaN,NaN,NaN,29.1197,high,chair,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
945,2011_002555.jpg,person,horse,NaN,NaN,NaN,29.2655,high,horse,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
946,2008_005347.jpg,chair,bottle,NaN,NaN,NaN,30.4249,high,chair,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
947,2010_001939.jpg,tvmonitor,diningtable,cat,NaN,NaN,29.8429,high,cat,NaN,...,Critical,tone1,448,space,0,None,None,None,0,16
948,2008_007057.jpg,dog,NaN,NaN,NaN,NaN,40.7731,high,dog,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
949,2008_000619.jpg,car,cat,NaN,NaN,NaN,33.4622,high,cat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
950,2011_000824.jpg,cat,NaN,NaN,NaN,NaN,31.7799,high,cat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
951,2008_000192.jpg,bird,NaN,NaN,NaN,NaN,29.1763,high,bird,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
952,2008_000833.jpg,car,boat,person,NaN,NaN,32.7593,high,boat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
953,2010_005106.jpg,person,aeroplane,NaN,NaN,NaN,30.2429,high,aeroplane,pottedplant,...,Normal,No tone,-999,space,0,q,0,-999,0,16
954,2011_001382.jpg,pottedplant,person,diningtable,bottle,NaN,28.9395,high,pottedplant,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
955,2008_007913.jpg,person,cat,NaN,NaN,NaN,32.2651,high,cat,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
956,2008_002084.jpg,pottedplant,person,dog,NaN,NaN,30.0074,high,dog,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
957,2010_004447.jpg,person,bottle,sofa,NaN,NaN,33.5612,high,bottle,NaN,...,Normal,No tone,-999,space,0,None,None,None,0,16
958,2008_002864.jpg,person,diningtable,bottle,NaN,NaN,36.4851,high,bottle,sofa,...,Normal,No tone,-999,space,0,q,0,-999,0,16
959,2011_002641.jpg,person,chair,bottle,NaN,NaN,33.3811,high,chair,chair,...,Normal,No tone,-999,space,0,q,0,-999,0,16
960,2010_002620.jpg,boat,NaN,NaN,NaN,NaN,34.9675,high,boat,NaN,...,Critical,tone2,536,space,0,None,None,None,0,16

In [50]:
df.loc[2,'RT_TO'] = None

In [40]:
df['RT_TO']

1        6.666
2        6.666
3        6.666
4        6.666
5        6.666
6        6.666
7        6.666
8        6.666
9        6.666
10       6.666
11       6.666
12       6.666
13       6.666
14       6.666
15       6.666
16       6.666
17       6.666
18       6.666
19       6.666
20       6.666
21       6.666
22       6.666
23       6.666
24       6.666
25       6.666
26       6.666
27       6.666
28       6.666
29       6.666
30       6.666
         ...
932      6.666
933      6.666
934      6.666
935      6.666
936      6.666
937      6.666
938      6.666
939      6.666
940      6.666
941      6.666
942      6.666
943      6.666
944      6.666
945      6.666
946      6.666
947      6.666
948      6.666
949      6.666
950      6.666
951      6.666
952      6.666
953      6.666
954      6.666
955      6.666
956      6.666
957      6.666
958      6.666
959      6.666
960      6.666
RT_TO      NaN
Name: RT_TO, Length: 961, dtype: object

In [26]:
df.loc['Image_Name',1]

KeyError: 'the label [Image_Name] is not in the [index]'

In [10]:
results = []
for o in observers:
    result = process_observer(o)
    results.append(result)

DIRTY! 2
DIRTY! 22
DIRTY! 24
FOUND RT IN FIRST 25
DIRTY! 91
DIRTY! 93
DIRTY! 107
DIRTY! 160
DIRTY! 172
DIRTY! 207
DIRTY! 209
FOUND RT IN FIRST 210
DIRTY! 242
DIRTY! 245
DIRTY! 253
DIRTY! 258
FOUND RT IN FIRST 259
DIRTY! 308
FOUND RT IN FIRST 309
DIRTY! 319
DIRTY! 322
DIRTY! 336
FOUND RT IN FIRST 337
DIRTY! 338
FOUND RT IN FIRST 339
DIRTY! 379
FOUND RT IN FIRST 380
DIRTY! 417
DIRTY! 440
DIRTY! 443
DIRTY! 451
DIRTY! 493
FOUND RT IN FIRST 494
DIRTY! 526
DIRTY! 532
DIRTY! 541
DIRTY! 548
FOUND RT IN FIRST 549
DIRTY! 637
FOUND RT IN FIRST 638
DIRTY! 646
DIRTY! 710
DIRTY! 761
DIRTY! 794
FOUND RT IN FIRST 795
DIRTY! 810
DIRTY! 828
DIRTY! 837
DIRTY! 841
DIRTY! 869
DIRTY! 901
DIRTY! 907
FOUND RT IN FIRST 908
DIRTY! 911
DIRTY! 929
DIRTY! 934
Take Over:
mean RT:  1.21444117647
SD:  0.250411800978
Outliers:  0
Visual Search:
mean RT:  0.929076388889
SD:  0.210972848433
Outliers:  4
2.19
1.462
1.478
1.816
0.759036144578
Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
keys               object
Trial_N_Block       int64
Block               int64
valid               int64
sdt                 int64
space              object
RT_TO             float64
RT_VS             float64
Acc_VS              int32
Acc_DT              int32
dtype: object
CC:
57 66
CC:
50 65
CC:
107 131
4    848
1     63
2     32
0     13
3      4
Name: sdt, dtype: int64
---------
4    422
1     34
2     14
0      8
3      2
Name: sdt, dtype: int64
---------
4    426
1     29
2     18
0      5
3      2
Name: sdt, dtype: int64
{'c': 1.0236959533474321, 'beta': 25.001776742370616, 'd': 3.1444364720910603, 'Ad': 0.98690734355292931}
{'c': 1.1507360331257703, 'beta': 28.035141494277774, 'd': 2.8968057666243325, 'Ad': 0.97973719051325792}
Load     Acc_VS
 'high'  0         0.941933
         1         0.925063
         666            NaN
         999       0.842571
 'low'   0         0.817675
         1         0.899212
         666       0.967000
         999       0.939200
Name: RT_VS, dtype: float64
Load     Acc_VS
 'high'  0         15
         1         50
         666        0
         999        7
 'low'   0          9
         1         57
         666        1
         999        5
Name: RT_VS, dtype: int64
Load     trial_type   Acc_DT
 'high'   'Critical'  0              NaN
                      1         0.736793
                      999       0.816000
          'Normal'    666       1.058500
                      999            NaN
 'low'    'Critical'  0              NaN
                      1         0.743588
          'Normal'    666       1.379000
                      999            NaN
Name: RT_TO, dtype: float64
Load     trial_type   Acc_DT
 'high'   'Critical'  0          18
                      1          29
                      999         1
          'Normal'    666         2
                      999       430
 'low'    'Critical'  0          14
                      1          34
          'Normal'    666         2
                      999       430
Name: Acc_DT, dtype: int64
DIRTY! 207
DIRTY! 283
DIRTY! 417
DIRTY! 440
FOUND RT IN SECOND 442
DIRTY! 726
DIRTY! 761
DIRTY! 766
DIRTY! 794
DIRTY! 804
DIRTY! 841
DIRTY! 901
DIRTY! 907
DIRTY! 911
DIRTY! 929
DIRTY! 934
Take Over:
mean RT:  1.24885882353
SD:  1.76767268831
Outliers:  1
-14.5
Visual Search:
mean RT:  1.75756944444
SD:  0.962669657867
Outliers:  4
4.389
4.474
8.16
4.55
0.872340425532
Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
keys               object
Trial_N_Block       int64
Block               int64
valid               int64
sdt                 int64
space              object
RT_TO             float64
RT_VS             float64
Acc_VS              int32
Acc_DT              int32
dtype: object
CC:
59 66
CC:
50 65
CC:
109 131
4    859
1     82
2     14
3      3
0      2
Name: sdt, dtype: int64
---------
4    430
1     43
2      5
3      2
Name: sdt, dtype: int64
---------
4    429
1     39
2      9
0      2
3      1
Name: sdt, dtype: int64
{'c': 0.67208443329700862, 'beta': 13.390916051725734, 'd': 3.8604919887202107, 'Ad': 0.99683117042719505}
{'c': 0.97155177859414188, 'beta': 37.02685097792302, 'd': 3.7173966752260359, 'Ad': 0.99571309742558678}
Load     Acc_VS
 'high'  0         2.091600
         1         1.549520
         666            NaN
         999       1.596571
 'low'   0         2.024224
         1         1.560605
         666       3.201000
         999       1.815000
Name: RT_VS, dtype: float64
Load     Acc_VS
 'high'  0         15
         1         50
         666        0
         999        7
 'low'   0          7
         1         59
         666        1
         999        5
Name: RT_VS, dtype: int64
Load     trial_type   Acc_DT
 'high'   'Critical'  0              NaN
                      1         1.089026
          'Normal'    666       0.792000
                      999            NaN
 'low'    'Critical'  0              NaN
                      1         0.935741
          'Normal'    666       0.494500
                      999            NaN
Name: RT_TO, dtype: float64
Load     trial_type   Acc_DT
 'high'   'Critical'  0           9
                      1          39
          'Normal'    666         1
                      999       431
 'low'    'Critical'  0           5
                      1          43
          'Normal'    666         2
                      999       430
Name: Acc_DT, dtype: int64
DIRTY! 107
DIRTY! 132
DIRTY! 175
DIRTY! 283
DIRTY! 440
DIRTY! 483
DIRTY! 612
DIRTY! 837
DIRTY! 841
Take Over:
mean RT:  1.18514772727
SD:  0.487979776494
Outliers:  1
-2.68
Visual Search:
mean RT:  1.09506944444
SD:  0.452403314606
Outliers:  4
2.426
3.78
2.274
2.525
0.901098901099
Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
keys               object
Trial_N_Block       int64
Block               int64
valid               int64
sdt                 int64
RT_TO             float64
RT_VS             float64
Acc_VS              int32
Acc_DT              int32
dtype: object
CC:
56 67
CC:
49 64
CC:
105 131
4    863
1     82
2      9
0      5
3      1
Name: sdt, dtype: int64
---------
4    432
1     42
2      3
0      3
Name: sdt, dtype: int64
---------
4    431
1     40
2      6
0      2
3      1
Name: sdt, dtype: int64
{'c': 0.77273364670290634, 'beta': 33.58615107765381, 'd': 4.5476391854938623, 'Ad': 0.99934929013628182}
{'c': 0.85369805132471555, 'beta': 29.291326265750364, 'd': 3.956072565786708, 'Ad': 0.99742394123298161}
Load     Acc_VS
 'high'  0         1.166071
         1         1.048309
         666       0.635000
         999       1.066429
 'low'   0         1.318734
         1         0.940661
         999       1.384800
Name: RT_VS, dtype: float64
Load     Acc_VS
 'high'  0         15
         1         49
         666        1
         999        7
 'low'   0         11
         1         56
         999        5
Name: RT_VS, dtype: int64
Load     trial_type   Acc_DT
 'high'   'Critical'  0              NaN
                      1         0.733825
                      999       0.665000
          'Normal'    666       1.185148
                      999            NaN
 'low'    'Critical'  0              NaN
                      1         0.758476
                      999       0.806000
          'Normal'    999            NaN
Name: RT_TO, dtype: float64
Load     trial_type   Acc_DT
 'high'   'Critical'  0           6
                      1          40
                      999         2
          'Normal'    666         1
                      999       431
 'low'    'Critical'  0           3
                      1          42
                      999         3
          'Normal'    999       432
Name: Acc_DT, dtype: int64
DIRTY! 172
DIRTY! 209
DIRTY! 242
DIRTY! 245
DIRTY! 308
DIRTY! 379
DIRTY! 433
DIRTY! 541
FOUND RT IN FIRST 542
DIRTY! 612
DIRTY! 663
DIRTY! 775
DIRTY! 810
DIRTY! 837
DIRTY! 878
DIRTY! 901
Take Over:
mean RT:  1.22903658537
SD:  0.343985835114
Outliers:  3
2.588
2.36
-0.22
Visual Search:
mean RT:  0.940208333333
SD:  0.283065434009
Outliers:  5
1.963
1.653
2.038
1.653
1.851
0.86170212766
Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
keys               object
Trial_N_Block       int64
Block               int64
valid               int64
sdt                 int64
space              object
RT_TO             float64
RT_VS             float64
Acc_VS              int32
Acc_DT              int32
dtype: object
CC:
63 67
CC:
52 65
CC:
115 132
4    863
1     81
2     14
0      2
Name: sdt, dtype: int64
---------
4    432
1     41
2      7
Name: sdt, dtype: int64
---------
4    431
1     40
2      7
0      2
Name: sdt, dtype: int64
{'c': 0.9960403938398924, 'beta': 59.429292505014274, 'd': 4.1010256912198901, 'Ad': 0.99813337149371661}
{'c': 1.0024247806907227, 'beta': 60.14589128747726, 'd': 4.0868633848936797, 'Ad': 0.99807286428715303}
Load     Acc_VS
 'high'  0         0.986894
         1         0.936196
         999       0.794857
 'low'   0         0.742500
         1         0.891571
         999       0.943642
Name: RT_VS, dtype: float64
Load     Acc_VS
 'high'  0         13
         1         52
         999        7
 'low'   0          4
         1         63
         999        5
Name: RT_VS, dtype: int64
Load     trial_type   Acc_DT
 'high'   'Critical'  0              NaN
                      1         0.777502
                      999       0.884000
          'Normal'    999            NaN
 'low'    'Critical'  0              NaN
                      1         0.786977
          'Normal'    999            NaN
Name: RT_TO, dtype: float64
Load     trial_type   Acc_DT
 'high'   'Critical'  0           7
                      1          40
                      999         1
          'Normal'    999       432
 'low'    'Critical'  0           7
                      1          41
          'Normal'    999       432
Name: Acc_DT, dtype: int64
DIRTY! 107
DIRTY! 322
DIRTY! 338
FOUND RT IN FIRST 339
DIRTY! 417
DIRTY! 451
DIRTY! 526
DIRTY! 559
DIRTY! 612
FOUND RT IN SECOND 614
DIRTY! 634
DIRTY! 646
DIRTY! 663
DIRTY! 710
DIRTY! 766
DIRTY! 794
DIRTY! 837
DIRTY! 841
DIRTY! 901
DIRTY! 911
DIRTY! 934
Take Over:
mean RT:  1.443625
SD:  0.831911359085
Outliers:  3
-1.87
3.726
-3.5
Visual Search:
mean RT:  1.16585416667
SD:  0.440441397425
Outliers:  5
2.875
2.557
3.208
2.578
2.396
0.846153846154
Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
keys               object
Trial_N_Block       int64
Block               int64
valid               int64
sdt                 int64
space              object
RT_TO             float64
RT_VS             float64
Acc_VS              int32
Acc_DT              int32
dtype: object
CC:
58 67
CC:
50 65
CC:
108 132
4    860
1     77
2     17
0      5
3      1
Name: sdt, dtype: int64
---------
4    430
1     38
2      8
0      3
3      1
Name: sdt, dtype: int64
---------
4    430
1     39
2      9
0      2
Name: sdt, dtype: int64
{'c': 0.94608942530917073, 'beta': 35.39515677151673, 'd': 3.7698074843721479, 'Ad': 0.99615809133836553}
{'c': 1.0790056964574586, 'beta': 69.61492385251219, 'd': 3.9323045109526693, 'Ad': 0.99728673164901804}
Load     Acc_VS
 'high'  0         1.021067
         1         1.122254
         999       0.949857
 'low'   0         1.262444
         1         1.099547
         666            NaN
         999       1.376971
Name: RT_VS, dtype: float64
Load     Acc_VS
 'high'  0         15
         1         50
         999        7
 'low'   0          9
         1         58
         666        0
         999        5
Name: RT_VS, dtype: int64
Load     trial_type   Acc_DT
 'high'   'Critical'  0              NaN
                      1         1.024221
          'Normal'    999            NaN
 'low'    'Critical'  0              NaN
                      1         1.050480
                      999       1.782500
          'Normal'    666       0.590000
                      999            NaN
Name: RT_TO, dtype: float64
Load     trial_type   Acc_DT
 'high'   'Critical'  0           9
                      1          39
          'Normal'    999       432
 'low'    'Critical'  0           8
                      1          38
                      999         2
          'Normal'    666         1
                      999       431
Name: Acc_DT, dtype: int64
DIRTY! 2
DIRTY! 12
DIRTY! 24
FOUND RT IN FIRST 25
DIRTY! 36
FOUND RT IN FIRST 37
DIRTY! 65
FOUND RT IN FIRST 66
DIRTY! 91
FOUND RT IN FIRST 92
DIRTY! 97
DIRTY! 125
FOUND RT IN FIRST 126
DIRTY! 132
FOUND RT IN FIRST 133
DIRTY! 160
DIRTY! 172
FOUND RT IN FIRST 173
DIRTY! 205
FOUND RT IN FIRST 206
DIRTY! 209
FOUND RT IN FIRST 210
DIRTY! 242
FOUND RT IN FIRST 243
DIRTY! 253
FOUND RT IN FIRST 254
DIRTY! 258
FOUND RT IN FIRST 259
DIRTY! 292
DIRTY! 308
FOUND RT IN FIRST 309
DIRTY! 319
FOUND RT IN FIRST 320
DIRTY! 322
DIRTY! 336
FOUND RT IN FIRST 337
DIRTY! 338
DIRTY! 359
DIRTY! 379
DIRTY! 384
FOUND RT IN FIRST 385
DIRTY! 433
FOUND RT IN FIRST 434
DIRTY! 440
DIRTY! 443
FOUND RT IN FIRST 444
DIRTY! 451
DIRTY! 463
DIRTY! 483
DIRTY! 493
FOUND RT IN FIRST 494
DIRTY! 522
FOUND RT IN FIRST 523
DIRTY! 526
DIRTY! 541
DIRTY! 548
FOUND RT IN FIRST 549
DIRTY! 551
DIRTY! 553
DIRTY! 566
DIRTY! 612
DIRTY! 634
DIRTY! 637
DIRTY! 646
DIRTY! 657
DIRTY! 663
DIRTY! 692
FOUND RT IN FIRST 693
DIRTY! 726
DIRTY! 741
DIRTY! 756
DIRTY! 761
FOUND RT IN FIRST 762
DIRTY! 775
DIRTY! 794
DIRTY! 804
DIRTY! 810
FOUND RT IN FIRST 811
DIRTY! 821
FOUND RT IN FIRST 822
DIRTY! 837
DIRTY! 846
DIRTY! 866
DIRTY! 869
FOUND RT IN FIRST 870
DIRTY! 881
FOUND RT IN FIRST 882
DIRTY! 901
FOUND RT IN FIRST 902
DIRTY! 907
FOUND RT IN FIRST 908
DIRTY! 911
FOUND RT IN FIRST 912
DIRTY! 929
FOUND RT IN FIRST 930
Take Over:
mean RT:  1.28123076923
SD:  0.345771902103
Outliers:  2
-0.25
2.219
Visual Search:
mean RT:  0.8764375
SD:  0.21037624096
Outliers:  4
1.647
1.456
1.455
1.411
0.96875
Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
keys               object
Trial_N_Block       int64
Block               int64
valid               int64
sdt                 int64
space              object
RT_TO             float64
RT_VS             float64
Acc_VS              int32
Acc_DT              int32
dtype: object
CC:
64 67
CC:
55 65
CC:
119 132
4    831
1     62
2     33
0     32
3      2
Name: sdt, dtype: int64
---------
4    416
1     34
0     15
2     14
3      1
Name: sdt, dtype: int64
---------
4    415
1     28
2     19
0     17
3      1
Name: sdt, dtype: int64
{'c': 1.1359461822971264, 'beta': 45.92139103022002, 'd': 3.3689369299904488, 'Ad': 0.99139518277349703}
{'c': 1.2886481782977055, 'beta': 51.71927262947524, 'd': 3.0619920600790151, 'Ad': 0.98481210479282455}
Load     Acc_VS
 'high'  0         0.988900
         1         0.888889
         666            NaN
         999       0.838286
 'low'   0         0.800667
         1         0.809701
         666            NaN
         999       0.975000
Name: RT_VS, dtype: float64
Load     Acc_VS
 'high'  0         10
         1         55
         666        0
         999        7
 'low'   0          3
         1         64
         666        0
         999        5
Name: RT_VS, dtype: int64
Load     trial_type   Acc_DT
 'high'   'Critical'  0              NaN
                      1         0.826723
                      999       1.132000
          'Normal'    666       1.281231
                      999            NaN
 'low'    'Critical'  0              NaN
                      1         0.806647
          'Normal'    666       0.549000
                      999            NaN
Name: RT_TO, dtype: float64
Load     trial_type   Acc_DT
 'high'   'Critical'  0          19
                      1          28
                      999         1
          'Normal'    666         1
                      999       431
 'low'    'Critical'  0          14
                      1          34
          'Normal'    666         1
                      999       431
Name: Acc_DT, dtype: int64
DIRTY! 12
FOUND RT IN FIRST 13
DIRTY! 15
FOUND RT IN FIRST 16
DIRTY! 24
FOUND RT IN FIRST 25
DIRTY! 36
FOUND RT IN FIRST 37
DIRTY! 65
FOUND RT IN FIRST 66
DIRTY! 107
DIRTY! 125
DIRTY! 160
FOUND RT IN FIRST 161
DIRTY! 172
FOUND RT IN FIRST 173
DIRTY! 175
DIRTY! 190
FOUND RT IN FIRST 191
DIRTY! 209
FOUND RT IN FIRST 210
DIRTY! 242
DIRTY! 253
DIRTY! 258
FOUND RT IN FIRST 259
DIRTY! 292
FOUND RT IN FIRST 293
DIRTY! 308
FOUND RT IN FIRST 309
DIRTY! 319
FOUND RT IN FIRST 320
DIRTY! 336
FOUND RT IN FIRST 337
DIRTY! 338
FOUND RT IN FIRST 339
DIRTY! 379
FOUND RT IN FIRST 380
DIRTY! 433
FOUND RT IN FIRST 434
DIRTY! 440
DIRTY! 443
FOUND RT IN FIRST 444
DIRTY! 451
FOUND RT IN FIRST 452
DIRTY! 463
FOUND RT IN FIRST 464
DIRTY! 493
FOUND RT IN FIRST 494
DIRTY! 532
FOUND RT IN FIRST 533
DIRTY! 541
FOUND RT IN FIRST 542
DIRTY! 548
FOUND RT IN FIRST 549
DIRTY! 612
FOUND RT IN FIRST 613
DIRTY! 637
FOUND RT IN FIRST 638
DIRTY! 663
DIRTY! 692
DIRTY! 710
DIRTY! 741
DIRTY! 761
FOUND RT IN FIRST 762
DIRTY! 794
FOUND RT IN FIRST 795
DIRTY! 804
DIRTY! 810
FOUND RT IN FIRST 811
DIRTY! 821
FOUND RT IN FIRST 822
DIRTY! 837
DIRTY! 901
FOUND RT IN FIRST 902
DIRTY! 907
FOUND RT IN FIRST 908
DIRTY! 911
DIRTY! 929
FOUND RT IN FIRST 930
Take Over:
mean RT:  1.27062650602
SD:  0.2799709413
Outliers:  3
2.003
1.989
2.168
Visual Search:
mean RT:  1.3383125
SD:  0.65561592615
Outliers:  4
3.043
4.108
3.994
5.682
1.33333333333
Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
keys               object
Trial_N_Block       int64
Block               int64
valid               int64
sdt                 int64
space              object
RT_TO             float64
RT_VS             float64
Acc_VS              int32
Acc_DT              int32
dtype: object
CC:
59 67
CC:
53 65
CC:
112 132
4    831
1     80
0     36
2     13
Name: sdt, dtype: int64
---------
4    416
1     42
0     17
2      5
Name: sdt, dtype: int64
---------
4    415
1     38
0     19
2      8
Name: sdt, dtype: int64
{'c': 0.894596866850212, 'beta': 46.05953905537339, 'd': 4.2811852229542975, 'Ad': 0.99876607203619117}
{'c': 1.0478246264782551, 'beta': 64.2832061521254, 'd': 3.9732778867103167, 'Ad': 0.99751931864096954}
Load     Acc_VS
 'high'  0         1.331635
         1         1.256717
         999       1.054571
 'low'   0         1.461164
         1         1.176441
         999       2.035263
Name: RT_VS, dtype: float64
Load     Acc_VS
 'high'  0         12
         1         53
         999        7
 'low'   0          8
         1         59
         999        5
Name: RT_VS, dtype: int64
Load     trial_type   Acc_DT
 'high'   'Critical'  0              NaN
                      1         0.809954
                      999       0.740000
          'Normal'    999            NaN
 'low'    'Critical'  0              NaN
                      1         0.799967
                      999       0.818000
          'Normal'    999            NaN
Name: RT_TO, dtype: float64
Load     trial_type   Acc_DT
 'high'   'Critical'  0           8
                      1          38
                      999         2
          'Normal'    999       432
 'low'    'Critical'  0           5
                      1          42
                      999         1
          'Normal'    999       432
Name: Acc_DT, dtype: int64
DIRTY! 2
FOUND RT IN FIRST 3
DIRTY! 12
DIRTY! 24
FOUND RT IN FIRST 25
DIRTY! 65
FOUND RT IN FIRST 66
DIRTY! 91
DIRTY! 107
DIRTY! 125
FOUND RT IN FIRST 126
DIRTY! 139
DIRTY! 160
FOUND RT IN FIRST 161
DIRTY! 172
FOUND RT IN FIRST 173
DIRTY! 190

In [16]:
import scipy

In [17]:
lows = [x['vs_accuracy_low'] for x in results]
highs = [x['vs_accuracy_high'] for x in results]

In [19]:
scipy.stats.ttest_rel(lows,highs)

Ttest_relResult(statistic=13.794897893969367, pvalue=6.2939446225113983e-10)

In [21]:
lows = [x['h_rate_low_detection'] for x in results]
highs = [x['h_rate_high_detection'] for x in results]
scipy.stats.ttest_rel(lows,highs)

Ttest_relResult(statistic=4.1965906619356135, pvalue=0.0007782444562446306)

In [5]:
cols = ['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','Load','exemplar','question','present_absent','trial_type','tone_Hz','tone_onset','space','RT_TO','keys','RT_VS','useless','Trial_N_Block','Block']

In [2]:
observers = ['p1','p2','p3','p4','p5','p6','p7','p8','p9','p10','p11','p12','p13','p14','p15','p16']

In [4]:
def dataframe_from_dict(DE):
    df = pd.DataFrame(index=DE.keys(), columns = cols)

    for t in DE.keys():
        row = [DE[t]['image_name'], 
            DE[t]['cat_1'],
               DE[t]['cat_2'],
               DE[t]['cat_3'],
               DE[t]['cat_4'],
               DE[t]['cat_5'],
               DE[t]['trueskill'],
               DE[t]['load'],
               DE[t]['exemplar'],
               DE[t]['question'],
               DE[t]['present_absent'],
               DE[t]['trial_type'],
               DE[t]['tone_hz'],
               DE[t]['tone_onset'],
               DE[t]['space'],
               DE[t]['RT_TO'],
               DE[t]['keys'],
               DE[t]['RT_VS'],
               DE[t]['useless'],
               0,
               DE[t]['block_number'],

        ]
        df.loc[t] = row
    return df

In [9]:
def calc_vs_accuracy(df, load_level):
    n = df.shape[0]
    count = 0
    correct = 0
    
    for i in range(n):
        pa = df.loc[i,'present_absent']
        sdt = df.loc[i,'sdt']
        keys = df.loc[i,'keys']
#         pdb.set_trace()
        if 'Normal' in df.loc[i, 'trial_type'] and sdt != 3 and load_level in df.loc[i,'Load']  and ('Target Present' in pa or 'Target Absent' in pa):
            count += 1
            if 'Target Present' in pa:
                if 'q' in keys:
                    c = True
                else:
                    c = False
            if 'Target Absent' in pa:
                if 'p' in keys:
                    c = True
                else:
                    c = False
           
            if c == True:
                correct += 1
#     set_trace()
    acc = correct/float(count)
    print 'CC:'
    print correct, count
    return acc

In [9]:
def calc_vs_accuracy_both(df):
    n = df.shape[0]
    count = 0
    correct = 0
    
    for i in range(n):
        pa = df.loc[i,'present_absent']
        sdt = df.loc[i,'sdt']
        keys = df.loc[i,'keys']
#         pdb.set_trace()
        if 'Normal' in df.loc[i, 'trial_type'] and sdt != 3  and ('Target Present' in pa or 'Target Absent' in pa):
            count += 1
            if 'Target Present' in pa:
                if 'q' in keys:
                    c = True
                else:
                    c = False
            if 'Target Absent' in pa:
                if 'p' in keys:
                    c = True
                else:
                    c = False
           
            if c == True:
                correct += 1
    acc = correct/float(count)
    print 'CC:'
    print correct, count
    return acc

In [27]:
f = '../output/participant_test.pik'
import pickle
with open(f,'r') as of:
    D = pickle.load(of)
df = dataframe_from_dict(D['experiment_details'])

In [28]:
len(df)

960

In [24]:
def process_observer_old(obs):
    f = '../output/participant_'+obs+'.pik'
    import pickle
    with open(f,'r') as of:
        D = pickle.load(of)
    df = dataframe_from_dict(D['experiment_details'])
    
    
       
    df['valid'] = df['Block']
    df['valid'] = 1
    df['sdt'] = 0
    df.drop(['Image_Name','
             Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','exemplar','question','space','useless'], axis=1, inplace=True)
    invalid_count = fix_reaction_times(df)
    
    RT_TO = df['RT_TO'].tolist()
    RT_VS = df['RT_VS'].tolist()
    Audio = df['trial_type'].tolist()
    Present_absent = df['present_absent'].tolist()
    Audio = df['trial_type'].tolist()
    Keys = df['keys'].tolist()
    Tone_onset = df['tone_onset'].tolist()

#     RT_TO = [str('NaN') if n == 'No timing' else float(n[0:5]) for n in RT_TO]
#     RT_VS = [str('NaN') if n == None else float(n[0:5])-1.3 for n in RT_VS]
#     Keys = [str(n[2:-1]) for n in Keys]
    RT_TO_floats = [n for n in RT_TO if type(n) == float]
    sd_TO = np.std(RT_TO_floats)
    mean_TO = np.mean(RT_TO_floats)

    #Getting rid of outliers for TO RT (outliers are replaced with mean)
    RT_TO_no_outliers = []
    counter_TO = 0
    RT_TO_outliers = []
    for i in RT_TO:
        if type(i) != float:
            RT_TO_no_outliers.append(i)
        elif type(i) == float:
            if (mean_TO - 2.5 * sd_TO) < i < (mean_TO + 2.5 * sd_TO):
                RT_TO_no_outliers.append(i)
            else:
                counter_TO = counter_TO + 1
                #print 'Outlier ' + str(counter_TO) + ': ' + str(i) 
                RT_TO_no_outliers.append(mean_TO)
                RT_TO_outliers.append(i)
    RT_TO = RT_TO_no_outliers

    Tone_onset = [int(n) for n in Tone_onset]
    for i in range(len(Tone_onset)):
        if Tone_onset[i] != -999:
            Tone_onset[i] = float(Tone_onset[i])/1000
            if type(RT_TO[i]) == float:
                #print RT_TO[i], '-', Tone_onset[i] 
                RT_TO[i] = RT_TO[i] - Tone_onset[i]
                #print RT_TO[i]


    RT_VS_floats = [n for n in RT_VS if type(n) == float]
    sd_VS = np.std(RT_VS_floats)
    mean_VS = np.mean(RT_VS_floats)

    #Getting rid of outliers for TO RT (outliers are replaced with mean)
    RT_VS_no_outliers = []
    counter_VS = 0
    RT_VS_outliers = []
    for i in RT_VS:
        if type(i) != float:
            RT_VS_no_outliers.append(i)
        elif type(i) == float:
            if (mean_VS - 2.5 * sd_VS) < i < (mean_VS + 2.5 * sd_VS):
                RT_VS_no_outliers.append(i)
            else:
                counter_VS = counter_VS + 1
                #print 'Outlier ' + str(counter_TO) + ': ' + str(i) 
                RT_VS_no_outliers.append(mean_VS)
                RT_VS_outliers.append(i)
    RT_VS = RT_VS_no_outliers

    print 'Take Over:'
    print 'mean RT: ', mean_TO
    print 'SD: ', sd_TO
    print 'Outliers: ', len(RT_TO_outliers)
    for i in RT_TO_outliers:
        print i

    print 'Visual Search:'
    print 'mean RT: ', mean_VS
    print 'SD: ', sd_VS
    print 'Outliers: ', len(RT_VS_outliers)
    for i in RT_VS_outliers:
        print i


    #######
    Acc_VS = []
    for i in range(960):
        if 'Critical' in Audio[i]:
            #print i
            Acc_VS.append('999')
        elif 'Normal' in Audio[i] and RT_TO[i] != 'NaN':
            Acc_VS.append('666')
        elif 'Target Present' in Present_absent[i] and 'q' in Keys[i]:
            Acc_VS.append(1)
        elif 'Target Present' in Present_absent[i] and 'p' in Keys[i]:
            Acc_VS.append(0)
        elif 'Target Absent' in Present_absent[i] and 'p' in Keys[i]:
            Acc_VS.append(1)   
        elif 'Target Absent' in Present_absent[i] and 'q' in Keys[i]:
            Acc_VS.append(0)
        elif 'No Target' in Present_absent[i]:
            Acc_VS.append('999')

    #print len(Acc_VS)
    #######

    #######
    # CREATING Acc_DT (1 = included for analysis; 0 = excluded from analysis)
    Acc_DT = []
    for i in range(960):
        if 'Critical' in Audio[i] and type(RT_TO[i]) != str:
            # Was visual search correct?
            if 'Target Present' in Present_absent[i] and 'q' in Keys[i]:
                Acc_DT.append(1)
                df.loc[i,'sdt'] = 1
            elif 'Target Absent' in Present_absent[i] and 'p' in Keys[i]:
                Acc_DT.append(1)
                df.loc[i,'sdt'] = 1
            elif 'Target Present' in Present_absent[i] and 'p' in Keys[i]:
                Acc_DT.append(999)
                df.loc[i,'sdt'] = 0
            elif 'Target Absent' in Present_absent[i] and 'q' in Keys[i]:
                Acc_DT.append(999)
                df.loc[i,'sdt'] = 0
            elif 'No Target' in Present_absent[i]:
                Acc_DT.append(1)
                df.loc[i,'sdt'] = 1

        # Incorrect on tone
        elif 'Critical' in Audio[i] and type(RT_TO[i]) == str:
            Acc_DT.append(0)
            df.loc[i,'sdt'] = 2
        #Throw out normal trials
        elif 'Normal' in Audio[i] and type(RT_TO[i]) != str:
            Acc_DT.append(666) # 666 are false alarms
            df.loc[i,'sdt'] = 3
        elif 'Normal' in Audio[i] and type(RT_TO[i]) == str:
            Acc_DT.append(999)
            df.loc[i,'sdt'] = 4
    for i in range(960):
        if df.loc[i,'valid'] == 0:
            df.loc[i,'sdt'] = 0
    #print len(Acc_DT) 

    correct_response_counter = len([n for n in Acc_DT if n == 1])
    incorrect_response_counter = len([n for n in Acc_DT if n == 0])
    incorrect_response_counter

    n_present = correct_response_counter + incorrect_response_counter
    hit_rate = float(correct_response_counter) / (n_present - invalid_count)
    print hit_rate

    # Converting lists into pandas.series...
    RT_TO = pd.Series(data=RT_TO)
    RT_VS = pd.Series(data=RT_VS)
    Acc_VS = pd.Series(data=Acc_VS)
    Acc_DT = pd.Series(data=Acc_DT)
    #False_Alarms = pd.Series(data=False_Alarms)
    # ...and combining them into a pandas dataframe

    df.drop(['RT_TO','RT_VS'], axis = 1, inplace = True)
    df['RT_TO'] = RT_TO.values
    df['RT_VS'] = RT_VS.values
    df['Acc_VS'] = Acc_VS.values
    df['Acc_DT'] = Acc_DT.values

    df[['RT_TO','RT_VS']] = df[['RT_TO','RT_VS']].astype('float')
    df[['Acc_VS','Acc_DT']] = df[['Acc_VS','Acc_DT']].astype('int')
    print df.dtypes

    df_low = df[df['Load'].str.contains("low")]
    df_high = df[df['Load'].str.contains("high")]

    counts = df['sdt'].value_counts()
    counts_low = df_low['sdt'].value_counts()
    counts_high = df_high['sdt'].value_counts()
    
    result['vs_accuracy_low'] = calc_vs_accuracy(df, 'low')
    result['vs_accuracy_high'] = calc_vs_accuracy(df, 'high')
    calc_vs_accuracy_both(df)
    
    print counts
    print '---------'
    print counts_low
    print '---------'
    print counts_high

    n_h = float(counts[1])
    n_m = float(counts[2])
    try:
        n_fa = float(counts[3])
    except:
        n_fa = 0
    n_cr = float(counts[4])

    h_rate = n_h / (n_h + n_m)
    fa_rate = n_fa / (n_cr + n_fa)
    h_rate

    n_h_low = float(counts_low[1])
    try:
        n_m_low = float(counts_low[2])
    except:
        n_m_low = 0
    try:
        n_fa_low = float(counts_low[3])
    except:
        n_fa_low = 0
    n_cr_low = float(counts_low[4])

    h_rate_low = n_h_low / (n_h_low + n_m_low)
    fa_rate_low = n_fa_low / (n_cr_low + n_fa_low)
    
    result['h_rate_low_detection'] = h_rate_low

    n_h_high = float(counts_high[1])
    try:
        n_m_high = float(counts_high[2])
    except:
        n_m_high = 0
    try:
        n_fa_high = float(counts_high[3])
    except:
        n_fa_high = 0
    n_cr_high = float(counts_high[4])

    h_rate_high = n_h_high / (n_h_high + n_m_high)
    fa_rate_high = n_fa_high / (n_cr_high + n_fa_high)
    
    result['h_rate_high_detection'] = h_rate_high

    print d_prime(n_h_low, n_m_low, n_fa_low, n_cr_low)
    print d_prime(n_h_high, n_m_high, n_fa_high, n_cr_high)

    #TABLE 1
    print df.groupby(['Load','Acc_VS']).RT_VS.mean()
    print df.groupby(['Load','Acc_VS']).RT_VS.count()

    # TABLE 2
    #print df.groupby(['Load','Acc_VS','present_absent']).RT_VS.mean()
    #print df.groupby(['Load','Acc_VS','present_absent']).RT_VS.count()

    #TABLE 3
    print df.groupby(['Load','trial_type','Acc_DT']).RT_TO.mean()
    print df.groupby(['Load','trial_type','Acc_DT']).Acc_DT.count()
    
    return result

In [3]:
def print_full(x):
    pd.set_option('display.max_rows', len(x))
    print(x)
    pd.reset_option('display.max_rows')

(480, 21)

In [5]:

#df2

(480, 21)

In [6]:

df

DIRTY! 2
DIRTY! 12
DIRTY! 24
FOUND RT IN FIRST 25
DIRTY! 36
FOUND RT IN FIRST 37
DIRTY! 65
FOUND RT IN FIRST 66
DIRTY! 91
FOUND RT IN FIRST 92
DIRTY! 97
DIRTY! 125
FOUND RT IN FIRST 126
DIRTY! 132
FOUND RT IN FIRST 133
DIRTY! 160
DIRTY! 172
FOUND RT IN FIRST 173
DIRTY! 205
FOUND RT IN FIRST 206
DIRTY! 209
FOUND RT IN FIRST 210
DIRTY! 242
FOUND RT IN FIRST 243
DIRTY! 253
FOUND RT IN FIRST 254
DIRTY! 258
FOUND RT IN FIRST 259
DIRTY! 292
DIRTY! 308
FOUND RT IN FIRST 309
DIRTY! 319
FOUND RT IN FIRST 320
DIRTY! 322
DIRTY! 336
FOUND RT IN FIRST 337
DIRTY! 338
DIRTY! 359
DIRTY! 379
DIRTY! 384
FOUND RT IN FIRST 385
DIRTY! 433
FOUND RT IN FIRST 434
DIRTY! 440
DIRTY! 443
FOUND RT IN FIRST 444
DIRTY! 451
DIRTY! 463
DIRTY! 483
DIRTY! 493
FOUND RT IN FIRST 494
DIRTY! 522
FOUND RT IN FIRST 523
DIRTY! 526
DIRTY! 541
DIRTY! 548
FOUND RT IN FIRST 549
DIRTY! 551
DIRTY! 553
DIRTY! 566
DIRTY! 612
DIRTY! 634
DIRTY! 637
DIRTY! 646
DIRTY! 657
DIRTY! 663
DIRTY! 692
FOUND RT IN FIRST 693
DIRTY! 726
DIRTY! 741
DIRTY! 756
DIRTY! 761
FOUND RT IN FIRST 762
DIRTY! 775
DIRTY! 794
DIRTY! 804
DIRTY! 810
FOUND RT IN FIRST 811
DIRTY! 821
FOUND RT IN FIRST 822
DIRTY! 837
DIRTY! 846
DIRTY! 866
DIRTY! 869
FOUND RT IN FIRST 870
DIRTY! 881
FOUND RT IN FIRST 882
DIRTY! 901
FOUND RT IN FIRST 902
DIRTY! 907
FOUND RT IN FIRST 908
DIRTY! 911
FOUND RT IN FIRST 912
DIRTY! 929
FOUND RT IN FIRST 930

,Load,present_absent,trial_type,tone_Hz,tone_onset,RT_TO,keys,RT_VS,Trial_N_Block,Block,valid,sdt,space
0,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',0,1,1,0,NaN
1,'low','Target Absent','Normal','No tone',-999,'No timing','p',2.235,1,1,1,0,NaN
2,'low','No Target','Critical','tone2',481,'No timing','Na','Na',2,1,1,0,NaN
3,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',3,1,1,0,NaN
4,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',4,1,1,0,NaN
5,'low','Target Present','Normal','No tone',-999,'No timing','q',2.355,5,1,1,0,NaN
6,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',6,1,1,0,NaN
7,'low','Target Present','Normal','No tone',-999,'No timing','p',2.241,7,1,1,0,NaN
8,'low','Target Absent','Normal','No tone',-999,'No timing','p',2.572,8,1,1,0,NaN
9,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',9,1,1,0,NaN
10,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',10,1,1,0,NaN
11,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',11,1,1,0,NaN
12,'low','No Target','Critical','tone2',631,'No timing','Na','Na',12,1,1,0,NaN
13,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',13,1,1,0,NaN
14,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',14,1,1,0,NaN
15,'low','No Target','Critical','tone2',305,0.944818019,'Na','Na',15,1,1,0,NaN
16,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',16,1,1,0,NaN
17,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',17,1,1,0,NaN
18,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',18,1,1,0,NaN
19,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',19,1,1,0,NaN
20,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',20,1,1,0,NaN
21,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',21,1,1,0,NaN
22,'low','No Target','Critical','tone1',78,0.878087262,'Na','Na',22,1,1,0,NaN
23,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',23,1,1,0,NaN
24,'low','No Target','Critical','tone2',946,1.644229233,'Na','Na',24,1,1,0,space
25,'low','No Target','Normal','No tone',-999,No timing,'Na','Na',25,1,0,0,No space
26,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',26,1,1,0,NaN
27,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',27,1,1,0,NaN
28,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',28,1,1,0,NaN
29,'low','No Target','Normal','No tone',-999,'No timing','Na','Na',29,1,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,'high','No Target','Normal','No tone',-999,No timing,'Na','Na',30,16,0,0,No space
931,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',31,16,1,0,NaN
932,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',32,16,1,0,NaN
933,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',33,16,1,0,NaN
934,'high','No Target','Critical','tone1',385,1.34208187,'Na','Na',34,16,1,0,NaN
935,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',35,16,1,0,NaN
936,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',36,16,1,0,NaN
937,'high','Target Present','Normal','No tone',-999,'No timing','q',2.008,37,16,1,0,NaN
938,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',38,16,1,0,NaN
939,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',39,16,1,0,NaN
940,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',40,16,1,0,NaN
941,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',41,16,1,0,NaN
942,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',42,16,1,0,NaN
943,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',43,16,1,0,NaN
944,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',44,16,1,0,NaN
945,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',45,16,1,0,NaN
946,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',46,16,1,0,NaN
947,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',47,16,1,0,NaN
948,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',48,16,1,0,NaN
949,'high','Target Present','Normal','No tone',-999,'No timing','q',1.976,49,16,1,0,NaN
950,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',50,16,1,0,NaN
951,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',51,16,1,0,NaN
952,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',52,16,1,0,NaN
953,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',53,16,1,0,NaN
954,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',54,16,1,0,NaN
955,'high','Target Present','Normal','No tone',-999,'No timing','q',1.892,55,16,1,0,NaN
956,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',56,16,1,0,NaN
957,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',57,16,1,0,NaN
958,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',58,16,1,0,NaN
959,'high','No Target','Normal','No tone',-999,'No timing','Na','Na',59,16,1,0,NaN

In [8]:
#RT_TO

Take Over:
mean RT:  1.28123076923
SD:  0.345771902103
Outliers:  2
-0.25
2.219
Visual Search:
mean RT:  0.8764375
SD:  0.21037624096
Outliers:  4
1.647
1.456
1.455
1.411

In [18]:
#for i in RT_TO:
#    print i, type(i)

In [21]:
# Calculating D' :
# to calculate D' prime you need:
#1) hit rate
#2) false alarms rate
# the z-transformed of 1 and 2
# the formula is:....
# 1 and 2 cannot be equal to 1 or 0

33

0.96875

In [23]:
n_present

95

In [24]:
correct_response_counter

62

Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
keys               object
Trial_N_Block       int64
Block               int64
valid               int64
sdt                 int64
space              object
RT_TO             float64
RT_VS             float64
Acc_VS              int32
Acc_DT              int32
dtype: object

4    831
1     62
2     33
0     32
3      2
Name: sdt, dtype: int64
---------
4    416
1     34
0     15
2     14
3      1
Name: sdt, dtype: int64
---------
4    415
1     28
2     19
0     17
3      1
Name: sdt, dtype: int64

0.6526315789473685

In [5]:
from __future__ import division # Not neccessary in Python 3 and later
from scipy.stats import norm
from math import exp,sqrt
Z = norm.ppf
 
def d_prime(hits, misses, fas, crs):
    # Floors an ceilings are replaced by half hits and half FA's
    halfHit = 0.5/(hits+misses)
    halfFa = 0.5/(fas+crs)
 
    # Calculate hitrate and avoid d' infinity
    hitRate = hits/(hits+misses)
    if hitRate == 1: hitRate = 1-halfHit
    if hitRate == 0: hitRate = halfHit
 
    # Calculate false alarm rate and avoid d' infinity
    faRate = fas/(fas+crs)
    if faRate == 1: faRate = 1-halfFa
    if faRate == 0: faRate = halfFa
 
    # Return d', beta, c and Ad'
    out = {}
    out['d'] = Z(hitRate) - Z(faRate)
    out['beta'] = exp((Z(faRate)**2 - Z(hitRate)**2)/2)
    out['c'] = -(Z(hitRate) + Z(faRate))/2
    out['Ad'] = norm.cdf(out['d']/sqrt(2))
    return out

In [35]:
#print d_prime(n_h, n_m, n_fa, n_cr)

{'c': 1.1359461822971264, 'beta': 45.92139103022002, 'd': 3.3689369299904488, 'Ad': 0.99139518277349703}
{'c': 1.2886481782977055, 'beta': 51.71927262947524, 'd': 3.0619920600790151, 'Ad': 0.98481210479282455}

In [36]:
# Calculating D' :
# to calculate D' prime you need:
#1) hit rate
#2) false alarms rate
# the z-transformed of 1 and 2
# the formula is:....
# 1 and 2 cannot be equal to 1 or 0

Load     Acc_VS
 'high'  0         0.988900
         1         0.888889
         666            NaN
         999       0.838286
 'low'   0         0.800667
         1         0.809701
         666            NaN
         999       0.975000
Name: RT_VS, dtype: float64
Load     Acc_VS
 'high'  0         10
         1         55
         666        0
         999        7
 'low'   0          3
         1         64
         666        0
         999        5
Name: RT_VS, dtype: int64
Load     trial_type   Acc_DT
 'high'   'Critical'  0              NaN
                      1         0.826723
                      999       1.132000
          'Normal'    666       1.281231
                      999            NaN
 'low'    'Critical'  0              NaN
                      1         0.806647
          'Normal'    666       0.549000
                      999            NaN
Name: RT_TO, dtype: float64
Load     trial_type   Acc_DT
 'high'   'Critical'  0          19
                      1          28
                      999         1
          'Normal'    666         1
                      999       431
 'low'    'Critical'  0          14
                      1          34
          'Normal'    666         1
                      999       431
Name: Acc_DT, dtype: int64

In [38]:
#with open('reports/test.html', 'wb') as file:
#    file.write('<html><table><tr><td>1</td></tr><tr><td>2</td></tr></table></html>')